# Generated by Django 3.2.13 on 2022-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('service', models.DateTimeField()),
                ('host', models.CharField(max_length=100)),
                ('user', models.CharField(default='guest', max_length=100)),
                ('method', models.CharField(max_length=6)),
                ('path', models.IntegerField(max_length=3)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
