# Generated by Django 3.2.13 on 2022-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20220526_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtype',
            name='name',
            field=models.CharField(max_length=7),
        ),
    ]
