# Generated by Django 3.2.13 on 2022-05-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APILogsModel',
        ),
    ]
