image: sue445/heroku-cli

stages:
  - deploy

heroku-deploy:
  stage: deploy  
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
  variables: 
    HEROKU_API_KEY: $HEROKU_API_KEY
  before_script:
    - apk add --update docker
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  script:
    - heroku container:push web --app=$HEROKU_APP_NAME
    - heroku container:release web --app=$HEROKU_APP_NAME
  environment:
    name: production
    url: https://$HEROKU_APP_NAME.herokuapp.com
