# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oauth_proto/resource.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aoauth_proto/resource.proto\x12\x0boauth_proto\"K\n\x10ResourceResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\"\x11\n\x0fResourceRequest2_\n\x0fResourceService\x12L\n\x0bGetResource\x12\x1c.oauth_proto.ResourceRequest\x1a\x1d.oauth_proto.ResourceResponse\"\x00\x62\x06proto3')



_RESOURCERESPONSE = DESCRIPTOR.message_types_by_name['ResourceResponse']
_RESOURCEREQUEST = DESCRIPTOR.message_types_by_name['ResourceRequest']
ResourceResponse = _reflection.GeneratedProtocolMessageType('ResourceResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCERESPONSE,
  '__module__' : 'oauth_proto.resource_pb2'
  # @@protoc_insertion_point(class_scope:oauth_proto.ResourceResponse)
  })
_sym_db.RegisterMessage(ResourceResponse)

ResourceRequest = _reflection.GeneratedProtocolMessageType('ResourceRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEREQUEST,
  '__module__' : 'oauth_proto.resource_pb2'
  # @@protoc_insertion_point(class_scope:oauth_proto.ResourceRequest)
  })
_sym_db.RegisterMessage(ResourceRequest)

_RESOURCESERVICE = DESCRIPTOR.services_by_name['ResourceService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESOURCERESPONSE._serialized_start=43
  _RESOURCERESPONSE._serialized_end=118
  _RESOURCEREQUEST._serialized_start=120
  _RESOURCEREQUEST._serialized_end=137
  _RESOURCESERVICE._serialized_start=139
  _RESOURCESERVICE._serialized_end=234
# @@protoc_insertion_point(module_scope)
